---
  - name: Update all existing packages using YUM
    yum: name=* state=latest
    when: ansible_os_family == 'RedHat'

  - name: Update APT repo and all existing packages
    apt: upgrade=dist update_cache=yes
    when: ansible_os_family == 'Debian'
